version: "3"

services:
  server:
    image: nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/django/static:/static
    ports:
      - "80:80"
    depends_on:
      - web
    links:
      - web
    environment:
      NGINX_PORT: 80

  web:
    tty: true
    stdin_open: true
    build:
      context: ./docker/django
    command: uwsgi --ini uwsgi.ini
    volumes:
      - ./docker/django/mainHP:/mainHP
      - ./docker/django/static:/static
      - ./docker/django:/uwsgi
    expose:
      - "8080"
